function signal = generate_signal_noisy(varargin)
% generate_signal_noisy
% Wrapper for baseline generator with explicit noise setting.

p = inputParser;
addParameter(p, 'noise_std', 0.05);
addParameter(p, 'fs', 100);
addParameter(p, 'duration', 60);
addParameter(p, 'f_true', 0.8);
addParameter(p, 'amplitude', 1.0);
addParameter(p, 'offset', 0.0);
addParameter(p, 'phase0', 0.0);
addParameter(p, 'decay', 0.0);
addParameter(p, 'seed', 1);
addParameter(p, 'outFile', '');
parse(p, varargin{:});

signal = generate_signal_baseline( ...
    'fs', p.Results.fs, ...
    'duration', p.Results.duration, ...
    'f_true', p.Results.f_true, ...
    'amplitude', p.Results.amplitude, ...
    'offset', p.Results.offset, ...
    'phase0', p.Results.phase0, ...
    'decay', p.Results.decay, ...
    'noise_std', p.Results.noise_std, ...
    'seed', p.Results.seed, ...
    'outFile', p.Results.outFile);
end
